name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./index2.html
          contents: |
            echo "Hello World!"
          write-mode: append
