name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        uses: "finnp/create-file-action@master"
          env:
            FILE_NAME: "fileName.txt"
            FILE_DATA: "file content"
